/**
  Markdeep diagrams; extracted from Markdeep.js Version 1.13
  Refined for use with nodejs


  Copyright 2015-2021, Morgan McGuire, https://casual-effects.com
  All rights reserved.

  -------------------------------------------------------------

  You may use, extend, and redistribute this code under the terms of
  the BSD license at https://opensource.org/licenses/BSD-2-Clause.
*/
// Mappings and constants used by markdeep.
// STROKE_WIDTH is set per-call inside diagramToSVG via options.strokeWidth
const DEFAULT_SCALE = 8;
const { min, max, abs, sign } = Math;
String.prototype.ss = String.prototype.substring;
String.prototype.rp = String.prototype.replace;

function escapeHTMLEntities(str) {
    return String(str).rp(/&/g, '&amp;').rp(/</g, '&lt;').rp(/>/g, '&gt;').rp(/"/g, '&quot;');
}

function strToArray(s) {
    return Array.from(s);
}

/**
   Adds whitespace at the end of each line of str, so that all lines have equal length in
   unicode characters (which is not the same as JavaScript characters when high-index/escape
   characters are present).
*/
function equalizeLineLengths(str) {
    const lineArray = str.split('\n');

    if ((lineArray.length > 0) && (lineArray[lineArray.length - 1] === '')) {
        // Remove the empty last line generated by split on a trailing newline
        lineArray.pop();
    }

    let longest = 0;
    lineArray.forEach(function (line) {
        longest = max(longest, strToArray(line).length);
    });

    // Worst case spaces needed for equalizing lengths
    // http://stackoverflow.com/questions/1877475/repeat-character-n-times
    const spaces = Array(longest + 1).join(' ');

    let result = '';
    lineArray.forEach(function (line) {
        // Append the needed number of spaces onto each line, and
        // reconstruct the output with newlines
        result += line + spaces.ss(strToArray(line).length) + '\n';
    });

    return result;
}

/** Finds the longest common whitespace prefix of all non-empty lines
    and then removes it */
function removeLeadingSpace(str) {
    const lineArray = str.split('\n');

    let minimum = Infinity;
    lineArray.forEach(function (line) {
        if (line.trim() !== '') {
            // This is a non-empty line
            const spaceArray = line.match(/^([ \t]*)/);
            if (spaceArray) {
                minimum = min(minimum, spaceArray[0].length);
            }
        }
    });

    if (minimum === 0) {
        // No leading space
        return str;
    }

    let result = '';
    lineArray.forEach(function (line) {
        // Strip the common spaces
        result += line.ss(minimum) + '\n';
    });

    return result;
}

/** Returns true if this character is a "letter" under the ASCII definition */
function isASCIILetter(c) {
    const code = c.charCodeAt(0);
    return ((code >= 65) && (code <= 90)) || ((code >= 97) && (code <= 122));
}

const MARKERS = { 'o': '\ue004', 'v': '\ue005', 'V': '\ue006' };

function hideChar(s, i) {
    const n = Object.keys(MARKERS).length;
    const r = new Array(n).fill('[a-zA-Z' + Object.values(MARKERS).join('') + ']');
    r[i] = '[' + Object.keys(MARKERS).join('') + ']';
    return s.replace(new RegExp(r.join(''), 'g'),
        v => v.substring(0, i) + MARKERS[v.charAt(i)] + v.substring(i + 1));
}

function unhideMarkers(s) {
    return Object.keys(MARKERS).reduce((acc, k) => acc.rp(new RegExp(MARKERS[k], 'g'), k), s);
}

function hideMarkers(s) {
    const n = Object.keys(MARKERS).length;
    s = Array.from({ length: n }, (_, i) => i).reduce((acc, i) => hideChar(acc, i), s);
    // Unhide strings that only contain 'o' or 'v'.
    // Note: Using \B as \ue00? is a non-word character.
    const allHidden = '\\B[' + Object.values(MARKERS).join('') + ']{' + n + ',}\\B';
    return s.replace(new RegExp(allHidden, 'g'), unhideMarkers);
}


/** Converts diagramString, which is a Markdeep diagram without the surrounding asterisks, to
    SVG (HTML). Lines may have ragged lengths.

    `options` is a dictionary with the following keys:

    backdrop (default: false) will add a white <rect> element as a backdrop so that
        the background of the image is not transparent
    disableText (default: false) will disable passing text
    showGrid (default: false) will display a debug grid
    spaces (default: 2) the number of spaces between different strings
    style (default: {}) a dictionary of attributes to attach to the <svg> element
 */
function diagramToSVG(diagramString, options) {
    // Clean up diagramString
    diagramString = equalizeLineLengths(removeLeadingSpace(diagramString));
    const originalString = diagramString;
    options = options || {};
    if (!Number.isInteger(options.spaces)) { options.spaces = 2; } // 0 is valid so falsy tests fail.
    options.arrow ??= 'solid';

    // Temporarily replace 'o', 'v', and 'V' if they are surrounded by other
    // text. Use another character to avoid processing them as decorations.
    // These will be swapped back in the final SVG.
    diagramString = hideMarkers(diagramString);

    /** Pixels per character */
    const SCALE = options.scale ?? DEFAULT_SCALE;

    /** SVG pixels from center to each line of a double line */
    const DOUBLE_LINE_GAP = SCALE / 4;

    const STROKE_WIDTH = options.strokeWidth ?? 1;

    /** Multiply Y coordinates by this when generating the final SVG
        result to account for the aspect ratio of text files. */
    const DEFAULT_ASPECT = 2;
    const ASPECT = options.aspect ?? DEFAULT_ASPECT;

    const DIAGONAL_ANGLE = Math.atan(1.0 / ASPECT) * 180 / Math.PI;

    const EPSILON = 1e-6;

    // The order of the following is based on rotation angles
    // and is used for ArrowSet.toSVG
    const ARROW_HEAD_CHARACTERS = '>v<^';
    const POINT_CHARACTERS = 'o*◌○◍●⊕';
    const JUMP_CHARACTERS = '()';
    const UNDIRECTED_VERTEX_CHARACTERS = "+";
    const VERTEX_CHARACTERS = UNDIRECTED_VERTEX_CHARACTERS + ".',`";

    // GRAY[i] is the Unicode block character for (i+1)/4 level gray
    const GRAY_CHARACTERS = '\u2591\u2592\u2593\u2588';

    // TRI[i] is a right-triangle rotated by 90*i
    const TRI_CHARACTERS = '\u25E2\u25E3\u25E4\u25E5';

    const DECORATION_CHARACTERS = ARROW_HEAD_CHARACTERS + POINT_CHARACTERS + JUMP_CHARACTERS + GRAY_CHARACTERS + TRI_CHARACTERS;

    function isUndirectedVertex(c) { return UNDIRECTED_VERTEX_CHARACTERS.indexOf(c) !== -1; }
    function isVertex(c) { return VERTEX_CHARACTERS.indexOf(c) !== -1; }
    function isTopVertex(c) { return isUndirectedVertex(c) || (c === '.') || (c === ','); }
    function isTopVertexOrDecoration(c) { return isTopVertex(c) || (c === '^'); }
    function isBottomVertex(c) { return isUndirectedVertex(c) || (c === "'") || (c === '`'); }
    function isVertexOrLeftDecoration(c) { return isVertex(c) || (c === '<') || isPoint(c); }
    function isVertexOrRightDecoration(c) { return isVertex(c) || (c === '>') || isPoint(c); }
    function isGray(c) { return GRAY_CHARACTERS.indexOf(c) + 1; }
    function isTri(c) { return TRI_CHARACTERS.indexOf(c) + 1; }

    // "D" = Diagonal slash (/), "B" = diagonal Backslash (\)
    // Characters that may appear anywhere on a solid line
    function isSolidHLine(c) { return (c === '-') || (c === '\u2501') || isUndirectedVertex(c) || isJump(c); }
    function isSquiggleHLine(c) { return (c === '~') || isUndirectedVertex(c) || isJump(c); }
    function isDoubleHLine(c) { return (c === '=') || (c === '\u2550') || isUndirectedVertex(c) || isJump(c); }
    function isSolidVLineOrJumpOrPoint(c) { return isSolidVLine(c) || isJump(c) || isPoint(c); }
    function isSolidVLine(c) { return (c === '|') || (c === '\u2503') || isUndirectedVertex(c); }
    function isSquiggleVLine(c) { return (c === '\u2307') || isUndirectedVertex(c); }
    function isDoubleVLine(c) { return (c === '\u2551') || (c === '\u2016') || isUndirectedVertex(c); }
    function isSolidDLine(c) { return (c === '/') || isUndirectedVertex(c) }
    function isSolidBLine(c) { return (c === '\\') || isUndirectedVertex(c); }
    function isJump(c) { return JUMP_CHARACTERS.indexOf(c) + 1; }
    function isPoint(c) { return POINT_CHARACTERS.indexOf(c) + 1; }
    function isDecoration(c) { return DECORATION_CHARACTERS.indexOf(c) + 1; }

    ///////////////////////////////////////////////////////////////////////////////
    // Math library
    function fp(x) { return x.toFixed(5).replace(/\.?0*$/, ''); }

    /** Invoke as new Vec2(v) to clone or new Vec2(x, y) to create from coordinates.
        Can also invoke without new for brevity. */
    function Vec2(x, y) {
        // Detect when being run without new
        if (!(this instanceof Vec2)) { return new Vec2(x, y); }

        if (y === undefined) {
            if (x === undefined) { x = y = 0; }
            else if (x instanceof Vec2) { y = x.y; x = x.x; }
            else { throw new Error("Vec2 requires one Vec2 or (x, y) as an argument"); }
        }
        this.x = x;
        this.y = y;
        Object.seal(this);
    }

    /** Returns coordinates */
    Vec2.prototype.coords = function () {
        return fp((this.x + 1) * SCALE) + ',' + fp((this.y + 1) * SCALE * ASPECT);
    }
    /** Returns an SVG representation, with a trailing space */
    Vec2.prototype.toString = Vec2.prototype.toSVG =
        function () { return this.coords() + ' '; };
    /** Return an offset Vec2 */
    Vec2.prototype.offset = function (dx, dy) { return Vec2(this.x + dx, this.y + dy); }

    /** Converts a "rectangular" string defined by newlines into 2D
        array of characters. Grids are immutable. */
    function makeGrid(str) {
        /** Returns ' ' for out of bounds values */
        const grid = function (x, y) {
            if (y === undefined) {
                if (x instanceof Vec2) { y = x.y; x = x.x; }
                else { throw new Error('grid requires either a Vec2 or (x, y)'); }
            }

            return ((x >= 0) && (x < grid.width) && (y >= 0) && (y < grid.height)) ?
                str[y * (grid.width + 1) + x] : ' ';
        };

        // Elements are true when consumed
        grid._used = [];

        grid.height = str.split('\n').length;
        if (str[str.length - 1] === '\n') { --grid.height; }

        // Convert the string to an array to better handle greater-than 16-bit unicode
        // characters, which JavaScript does not process correctly with indices. Do this after
        // the above string processing.
        str = strToArray(str);
        grid.width = str.indexOf('\n');

        grid.hasText = function () {
            return str.some((x, i) => !(x === ' ' || x === '\n') && !grid._used[i]);
        }

        grid.v = function (x, y) {
            return ((x >= 0) && (x < grid.width) && (y >= 0) && (y < grid.height)) ?
                str[y * (grid.width + 1) + x] : ' ';
        };

        /** Mark this location. Takes a Vec2 or (x, y) */
        grid.setUsed = function (x, y) {
            if (y === undefined) {
                if (x instanceof Vec2) { y = x.y; x = x.x; }
                else { throw new Error('grid requires either a Vec2 or (x, y)'); }
            }
            if ((x >= 0) && (x < grid.width) && (y >= 0) && (y < grid.height)) {
                // Match the source string indexing
                grid._used[y * (grid.width + 1) + x] = true;
            }
        };

        grid.isUsed = function (x, y) {
            if (y === undefined) {
                if (x instanceof Vec2) { y = x.y; x = x.x; }
                else { throw new Error('grid requires either a Vec2 or (x, y)'); }
            }
            return !!this._used[y * (this.width + 1) + x];
        };

        /** Returns the x offset of the next run of text on the line;
            returns this.width if there is no text. */
        grid.textStart = function (x, y) {
            for (; x < this.width; ++x) {
                if (this.isUsed(x, y)) { continue; }
                if (this(x, y) !== ' ') { break; }
            }
            return x;
        }

        /** Returns the text at the given location, marking these locations as used. */
        grid.text = function (x, y) {
            let spaces = 0;
            let end = x;
            for (; end < this.width; ++end) {
                if (this.isUsed(end, y)) {
                    break;
                }
                if (this(end, y) === ' ') {
                    spaces++;
                } else {
                    spaces = 0;
                }
                if (spaces >= options.spaces) {
                    end++;
                    break;
                }
            }
            end -= spaces;
            for (let i = x; i < end; ++i) {
                this._used[y * (this.width + 1) + i] = true;
            }
            return str.slice(y * (this.width + 1) + x, y * (this.width + 1) + end);
        }

        /** Returns true if there is a solid vertical line passing through (x, y) */
        grid.isVLineAt = function (x, y, f, short) {
            if (y === undefined) { y = x.x; x = x.x; }

            const up = grid(x, y - 1);
            const c = grid(x, y);
            const dn = grid(x, y + 1);

            const uprt = grid(x + 1, y - 1);
            const uplt = grid(x - 1, y - 1);

            if (f(c)) {
                // Looks like a vertical line...does it continue?
                return (isTopVertexOrDecoration(up) || f(up) || isJump(up) ||
                    isBottomVertex(dn) || (dn === 'v') || f(dn) || isJump(dn) ||
                    isPoint(up) || isPoint(dn) || (up === '_') || (uplt === '_') ||
                    (uprt === '_') ||
                    // Special case of 1-high vertical on two curved corners
                    ((isTopVertex(uplt) || isTopVertex(uprt)) &&
                        (isBottomVertex(grid(x - 1, y + 1)) || isBottomVertex(grid(x + 1, y + 1)))));

            } else if (isTopVertex(c) || (c === '^')) {
                // May be the top of a vertical line
                return (f(dn) || (isJump(dn) && (c !== '.'))) &&
                    (c !== '^' || (up !== 'v' && up !== 'V'));
            } else if (isBottomVertex(c) || (c === 'v' || c === 'V')) {
                return f(up) || (isJump(up) && (c !== "'")) ||
                    ((up === 'v' || up === 'V') && f(grid(x, y - 2)));
            } else if (isPoint(c)) {
                return f(up) || f(dn);
            }

            return false;
        };
        grid.isSolidVLineAt = function (x, y) {
            return grid.isVLineAt(x, y, isSolidVLine, true);
        };
        grid.isSquiggleVLineAt = function (x, y) {
            return grid.isVLineAt(x, y, isSquiggleVLine, false);
        };
        grid.isDoubleVLineAt = function (x, y) {
            return grid.isVLineAt(x, y, isDoubleVLine, false);
        };

        /** Returns true if there is a solid middle (---) horizontal line
            passing through (x, y). Ignores underscores. */
        grid.isHLineAt = function (x, y, f) {
            if (y === undefined) { y = x.x; x = x.x; }

            const ltlt = grid(x - 2, y);
            const lt = grid(x - 1, y);
            const c = grid(x + 0, y);
            const rt = grid(x + 1, y);
            const rtrt = grid(x + 2, y);

            if (f(c) || (f(lt) && isJump(c))) {
                // Looks like a horizontal line...does it continue? We need three in a row.
                if (f(lt)) {
                    return f(rt) || isVertexOrRightDecoration(rt) || f(ltlt) || isVertexOrLeftDecoration(ltlt);
                } else if (isVertexOrLeftDecoration(lt)) {
                    return f(rt);
                } else {
                    return f(rt) && (f(rtrt) || isVertexOrRightDecoration(rtrt));
                }

            } else if (c === '<') {
                return f(rt) && f(rtrt) && (lt !== '>');
            } else if (c === '>') {
                return f(ltlt) && (f(lt) || (lt === '>'));
            } else if (isVertex(c)) {
                return ((f(lt) && f(ltlt)) || (f(rt) && f(rtrt)));
            }

            return false;
        };
        grid.isSolidHLineAt = function (x, y) {
            return this.isHLineAt(x, y, isSolidHLine);
        };
        grid.isSquiggleHLineAt = function (x, y) {
            return this.isHLineAt(x, y, isSquiggleHLine);
        };
        grid.isDoubleHLineAt = function (x, y) {
            return this.isHLineAt(x, y, isDoubleHLine);
        };
        grid.isAnyHLineAt = function (x, y) {
            return this.isHLineAt(x, y, isSolidHLine) || this.isHLineAt(x, y, isSquiggleHLine) || this.isHLineAt(x, y, isDoubleHLine);
        };


        /** Returns true if there is a solid backslash line passing through (x, y) */
        grid.isSolidBLineAt = function (x, y) {
            if (y === undefined) { y = x.x; x = x.x; }
            const c = grid(x, y);
            const lt = grid(x - 1, y - 1);
            const rt = grid(x + 1, y + 1);

            if (c === '\\') {
                // Looks like a diagonal line...does it continue? We need two in a row.
                return (isSolidBLine(rt) || isBottomVertex(rt) || isPoint(rt) || (rt === 'v' || rt === 'V') ||
                    isSolidBLine(lt) || isTopVertex(lt) || isPoint(lt) || (lt === '^') ||
                    (grid(x, y - 1) === '/') || (grid(x, y + 1) === '/') || (rt === '_') || (lt === '_') ||
                    (grid(x + 1, y) === '/' && grid(x - 1, y - 1) === '_') ||
                    (grid(x - 1, y) === '/' && grid(x + 1, y) === '_'));
            } else if (c === '.') {
                return (rt === '\\');
            } else if (c === "'") {
                return (lt === '\\');
            } else if (c === '^') {
                return rt === '\\';
            } else if (c === 'v' || c === 'V') {
                return lt === '\\';
            } else if (isVertex(c) || isPoint(c) || (c === '|')) {
                return isSolidBLine(lt) || isSolidBLine(rt);
            }
        };


        /** Returns true if there is a solid diagonal line passing through (x, y) */
        grid.isSolidDLineAt = function (x, y) {
            if (y === undefined) { y = x.x; x = x.x; }

            const c = grid(x, y);
            const lt = grid(x - 1, y + 1);
            const rt = grid(x + 1, y - 1);

            if (c === '/' && ((grid(x, y - 1) === '\\') || (grid(x, y + 1) === '\\'))) {
                // Special case of tiny hexagon corner
                return true;
            } else if (c === '/' && ((grid(x + 1, y) === '\\' && grid(x - 1, y) === '_') ||
                (grid(x - 1, y) === '\\' && grid(x + 1, y - 1) === '_'))) {
                // _/\ or   _
                //        \/
                return true;
            } else if (isSolidDLine(c)) {
                // Looks like a diagonal line...does it continue? We need two in a row.
                return (isSolidDLine(rt) || isTopVertex(rt) || isPoint(rt) || (rt === '^') || (rt === '_') ||
                    isSolidDLine(lt) || isBottomVertex(lt) || isPoint(lt) || (lt === 'v' || lt === 'V') || (lt === '_'));
            } else if (c === '.' || c === ',') {
                return (lt === '/');
            } else if (c === "'") {
                return (rt === '/');
            } else if (c === '^') {
                return lt === '/';
            } else if (c === 'v' || c === 'V') {
                return rt === '/';
            } else if (isVertex(c) || isPoint(c) || (c === '|')) {
                return isSolidDLine(lt) || isSolidDLine(rt);
            }
            return false;
        };

        grid.toString = function () { return str; };

        return Object.freeze(grid);
    }


    /** A 1D curve. If C is specified, the result is a bezier with
        that as the tangent control point */
    function Path(A, B, C, D, style) {
        if (!((A instanceof Vec2) && (B instanceof Vec2))) {
            throw new Error('Path constructor requires at least two Vec2s');
        }
        this.A = A;
        this.B = B;
        if (C) {
            this.C = C;
            if (D) {
                this.D = D;
            } else {
                this.D = C;
            }
        }

        this.dashed = style === 'dashed' || false;
        this.double = style === 'double' || false;
        this.squiggle = style === 'squiggle' || false;

        this.arrowAtA = null;
        this.arrowAtB = null;
        this.arrowTipAtA = null;
        this.arrowTipAtB = null;
    }

    const _ = Path.prototype;
    _.isVertical = function () {
        return this.B.x === this.A.x;
    };

    _.isHorizontal = function () {
        return this.B.y === this.A.y;
    };

    /** Diagonal lines look like: / See also backDiagonal */
    _.isDiagonal = function () {
        const dx = this.B.x - this.A.x;
        const dy = this.B.y - this.A.y;
        return (abs(dy + dx) < EPSILON);
    };

    _.isBackDiagonal = function () {
        const dx = this.B.x - this.A.x;
        const dy = this.B.y - this.A.y;
        return (abs(dy - dx) < EPSILON);
    };

    _.isCurved = function () {
        return this.C !== undefined;
    };

    /** Does this path have any end at (x, y) */
    _.endsAt = function (x, y) {
        if (y === undefined) { y = x.y; x = x.x; }
        return ((this.A.x === x) && (this.A.y === y)) ||
            ((this.B.x === x) && (this.B.y === y));
    };

    /** Does this path have an up end at (x, y) */
    _.upEndsAt = function (x, y) {
        if (y === undefined) { y = x.y; x = x.x; }
        return this.isVertical() && (this.A.x === x) && (min(this.A.y, this.B.y) === y);
    };

    /** Does this path have an up end at (x, y) */
    _.diagonalUpEndsAt = function (x, y) {
        if (!this.isDiagonal()) { return false; }
        if (y === undefined) { y = x.y; x = x.x; }
        if (this.A.y < this.B.y) {
            return (this.A.x === x) && (this.A.y === y);
        } else {
            return (this.B.x === x) && (this.B.y === y);
        }
    };

    /** Does this path have a down end at (x, y) */
    _.diagonalDownEndsAt = function (x, y) {
        if (!this.isDiagonal()) { return false; }
        if (y === undefined) { y = x.y; x = x.x; }
        if (this.B.y < this.A.y) {
            return (this.A.x === x) && (this.A.y === y);
        } else {
            return (this.B.x === x) && (this.B.y === y);
        }
    };

    /** Does this path have an up end at (x, y) */
    _.backDiagonalUpEndsAt = function (x, y) {
        if (!this.isBackDiagonal()) { return false; }
        if (y === undefined) { y = x.y; x = x.x; }
        if (this.A.y < this.B.y) {
            return (this.A.x === x) && (this.A.y === y);
        } else {
            return (this.B.x === x) && (this.B.y === y);
        }
    };

    /** Does this path have a down end at (x, y) */
    _.backDiagonalDownEndsAt = function (x, y) {
        if (!this.isBackDiagonal()) { return false; }
        if (y === undefined) { y = x.y; x = x.x; }
        if (this.B.y < this.A.y) {
            return (this.A.x === x) && (this.A.y === y);
        } else {
            return (this.B.x === x) && (this.B.y === y);
        }
    };

    /** Does this path have a down end at (x, y) */
    _.downEndsAt = function (x, y) {
        if (y === undefined) { y = x.y; x = x.x; }
        return this.isVertical() && (this.A.x === x) && (max(this.A.y, this.B.y) === y);
    };

    /** Does this path have a left end at (x, y) */
    _.leftEndsAt = function (x, y) {
        if (y === undefined) { y = x.y; x = x.x; }
        return this.isHorizontal() && (this.A.y === y) && (min(this.A.x, this.B.x) === x);
    };

    /** Does this path have a right end at (x, y) */
    _.rightEndsAt = function (x, y) {
        if (y === undefined) { y = x.y; x = x.x; }
        return this.isHorizontal() && (this.A.y === y) && (max(this.A.x, this.B.x) === x);
    };

    _.verticalPassesThrough = function (x, y) {
        if (y === undefined) { y = x.y; x = x.x; }
        return this.isVertical() &&
            (this.A.x === x) &&
            (min(this.A.y, this.B.y) <= y) &&
            (max(this.A.y, this.B.y) >= y);
    }

    _.horizontalPassesThrough = function (x, y) {
        if (y === undefined) { y = x.y; x = x.x; }
        return this.isHorizontal() &&
            (this.A.y === y) &&
            (min(this.A.x, this.B.x) <= x) &&
            (max(this.A.x, this.B.x) >= x);
    }

    /** Mark that an arrowhead is at endpoint A or B matching (x, y).
     *  type is 'end' (arrowhead terminates the path) or 'cont' (arrowhead passes through).
     *  tip is the Vec2 position of the arrowhead tip (accounting for arrow center and rotation). */
    _.markArrowAt = function (x, y, type, tip) {
        if (this.A.x === x && this.A.y === y) {
            if (type !== 'cont' || this.arrowAtA !== 'end') {
                this.arrowAtA = type;
                this.arrowTipAtA = tip;
            }
        } else if (this.B.x === x && this.B.y === y) {
            if (type !== 'cont' || this.arrowAtB !== 'end') {
                this.arrowAtB = type;
                this.arrowTipAtB = tip;
            }
        }
    };

    /** Mark that an arrowhead passes through this path, pointing toward the right endpoint */
    _.markArrowContRight = function (tip) {
        if (this.A.x >= this.B.x) { this.markArrowAt(this.A.x, this.A.y, 'cont', tip); }
        else { this.markArrowAt(this.B.x, this.B.y, 'cont', tip); }
    };

    /** Mark that an arrowhead passes through this path, pointing toward the left endpoint */
    _.markArrowContLeft = function (tip) {
        if (this.A.x <= this.B.x) { this.markArrowAt(this.A.x, this.A.y, 'cont', tip); }
        else { this.markArrowAt(this.B.x, this.B.y, 'cont', tip); }
    };

    /** Mark that an arrowhead passes through this path, pointing toward the upper endpoint */
    _.markArrowContUp = function (tip) {
        if (this.A.y <= this.B.y) { this.markArrowAt(this.A.x, this.A.y, 'cont', tip); }
        else { this.markArrowAt(this.B.x, this.B.y, 'cont', tip); }
    };

    /** Mark that an arrowhead passes through this path, pointing toward the lower endpoint */
    _.markArrowContDown = function (tip) {
        if (this.A.y >= this.B.y) { this.markArrowAt(this.A.x, this.A.y, 'cont', tip); }
        else { this.markArrowAt(this.B.x, this.B.y, 'cont', tip); }
    };

    // 1.5 is the length, 0.35 is the offset from the central line for an the arrowhead.
    // Rather than drawa the line to the end of the arrow, we need to pull it back slightly
    // to account for its width.  Otherwise, we get a round blob on the end.
    //  ---    .
    //   ^     | `-._
    //  0.35   |     `-._
    //   v  ---+---------`-._
    //  ---      line  •  )  _>
    //      ---+---------.-'
    //         |      .-'
    //         :
    //         |<---- 1.5 ---->|
    // That means moving the dot back from the end.
    // Based on similar triangles, we need to scale STROKE_WIDTH/2
    // (the perpendicular distance from our target point to the edge of the arrowhead)
    // by the ratio of the hypotenuse (√...BASE² + ...LENGTH²)
    // divided by the length of the matching side (...BASE=0.35).
    // The ...BASE value being set to ...HALF_BASE * ASPECT,
    // to account for the distortion in SVG space.
    const ARROWHEAD_HALF_BASE = 0.35;
    const ARROWHEAD_LENGTH = 1.5;
    const ARROWHEAD_HYPOT = Math.sqrt((ASPECT * ARROWHEAD_HALF_BASE) ** 2 + ARROWHEAD_LENGTH ** 2);
    const ARROWHEAD_TIP_ADJUST = STROKE_WIDTH / 2 * ARROWHEAD_HYPOT / (ARROWHEAD_HALF_BASE * ASPECT);

    _.offsetLine = function (dx, dy) {
        // Unit vector in SVG pixel space, normalized by SVG-space distance (accounts for aspect ratio).
        // ux, uy are the per-SVG-pixel step in grid coordinates.
        const vx = this.B.x - this.A.x;
        const vy = this.B.y - this.A.y;
        const s_asp = Math.sqrt(vx ** 2 + (vy * ASPECT) ** 2);
        const ux = vx / (s_asp * SCALE);
        const uy = vy / (s_asp * SCALE);

        // SVG-space perpendicular offset of this stroke from the path centre.
        // For an offset (double-line) stroke the outer edge must fit inside the arrowhead,
        // requiring extra pullback of d_SVG * ARROWHEAD_LEN / ARROWHEAD_HALF_BASE / ASPECT SVG pixels
        // (= d_SVG / tan(half-angle) in SVG space, where half-angle is the arrowhead slope).
        // Applying via ux/uy (which carry the inverse ASPECT factor) keeps the result correct
        // for both horizontal and vertical paths without any special-casing.
        const d_SVG = SCALE * Math.sqrt(dx ** 2 + (dy * ASPECT) ** 2);
        const adjust = ARROWHEAD_TIP_ADJUST + d_SVG * ARROWHEAD_LENGTH / ARROWHEAD_HALF_BASE / ASPECT;

        let a = (this.arrowTipAtA ?? this.A).offset(dx, dy);
        if (this.arrowTipAtA && this.arrowAtA !== 'none') {
            // Move the stroke endpoint toward B by adjust SVG pixels so the round cap
            // is tangent to (and hidden inside) the arrowhead body.
            a = a.offset(ux * adjust, uy * adjust);
        }
        let svg = '<path d="M ' + a.coords();
        if (this.isCurved()) {
            svg += 'C ' + this.C.offset(dx, dy) + this.D.offset(dx, dy);
        } else {
            svg += 'L ';
        }
        let b = (this.arrowTipAtB ?? this.B).offset(dx, dy);
        if (this.arrowTipAtB && this.arrowAtB !== 'none') {
            b = b.offset(-ux * adjust, -uy * adjust);
        }
        svg += b.coords() + '"';
        if (this.dashed) {
            svg += ' class="dashed"';
        }
        svg += '/>';
        return svg;
    }

    _.squigglePath = function () {
        const vx = this.B.x - this.A.x;
        const vy = this.B.y - this.A.y;
        // Unit vector.
        const base_len = Math.sqrt(vx ** 2 + vy ** 2);
        const dx = vx / base_len;
        const dy = vy / base_len;

        // Grid-space unit vector.
        const g_len = Math.sqrt(vx ** 2 + (vy * ASPECT) ** 2);
        const g_dx = vx / (g_len * SCALE);
        const g_dy = vy / (g_len * SCALE);

        const hasArrowA = !!(this.arrowTipAtA && this.arrowAtA !== 'none');
        const hasArrowB = !!(this.arrowTipAtB && this.arrowAtB !== 'none');

        const ATT = ARROWHEAD_TIP_ADJUST;
        let pathStart = this.arrowTipAtA ?? this.A;
        let pathEnd = this.arrowTipAtB ?? this.B;
        if (hasArrowA) { pathStart = pathStart.offset(g_dx * ATT, g_dy * ATT); }
        if (hasArrowB) { pathEnd = pathEnd.offset(-g_dx * ATT, -g_dy * ATT); }

        // L: path length in grid units, projected along the line direction.
        // Picks up the arrowhead extension automatically (+1 for horizontal,
        // +0.5 for vertical, regardless of ASPECT, per arrowTip() geometry), minus ATT pullback.
        const len = (pathEnd.x - pathStart.x) * dx + (pathEnd.y - pathStart.y) * dy;

        // At each arrowhead end a half squiggle (0.5 units) replaces the straight margin.
        const halfA = hasArrowA ? 0.5 : 0;
        const halfB = hasArrowB ? 0.5 : 0;
        const n = Math.floor(Math.max(0, len - halfA - halfB));

        // Compute margins, which will be straight lines.
        // Place margins at the arrow end(s), not the free end.
        // With no arrows, split the margin to either end.
        const margin = len - halfA - n - halfB;
        let margin_a, margin_b;
        if (hasArrowA && !hasArrowB) {
            margin_a = margin;
            margin_b = 0;
        } else if (hasArrowB && !hasArrowA) {
            margin_a = 0;
            margin_b = margin;
        } else {
            margin_a = margin / 2;
            margin_b = margin / 2;
        }

        // SVG-pixel offsets: quarter-cell along the line, and perpendicular amplitude
        const ax = dx * 0.25 * SCALE;
        const ay = dy * 0.25 * SCALE * ASPECT;
        const SQUIGGLE_AMPLITUDE = 0.2 * SCALE * ASPECT;
        const px = vy * ASPECT / g_len * SQUIGGLE_AMPLITUDE;
        const py = vx / g_len * SQUIGGLE_AMPLITUDE;

        const q1 = 'q ' + fp(ax + px) + ',' + fp(ay - py) + ' ' + fp(2 * ax) + ',' + fp(2 * ay) + ' ';
        const q2 = 'q ' + fp(ax - px) + ',' + fp(ay + py) + ' ' + fp(2 * ax) + ',' + fp(2 * ay) + ' ';

        let svg = '<path d="M ' + pathStart.coords();
        if (margin_a > 0) {
            svg += ' l ' + fp(margin_a * dx * SCALE) + ',' + fp(margin_a * dy * SCALE * ASPECT) + ' ';
        }
        if (hasArrowA) svg += q2;
        for (let i = 0; i < n; i++) svg += q1 + q2;
        if (hasArrowB) svg += q1;
        if (margin_b > 0) {
            svg += 'l ' + fp(margin_b * dx * SCALE) + ',' + fp(margin_b * dy * SCALE * ASPECT);
        }
        svg += '"/>';
        return svg;
    }

    /** Returns a string suitable for inclusion in an SVG tag */
    _.toSVG = function () {
        let svg = '';
        if (this.double) {
            let dx = this.B.x - this.A.x;
            let dy = this.B.y - this.A.y;
            const s = Math.sqrt(dx ** 2 + dy ** 2);
            // Nudges each line DOUBLE_LINE_GAP SVG pixels away from the center.
            // Scale the y coordinate by the geo-mean of ASPECT and its default,
            // which makes the spread less problematic for odd aspect ratios.
            dx /= s * SCALE * Math.sqrt(ASPECT * DEFAULT_ASPECT) / DOUBLE_LINE_GAP;
            dy /= s * SCALE / DOUBLE_LINE_GAP;
            svg += this.offsetLine(dy, -dx);
            svg += this.offsetLine(-dy, dx);
        } else if (this.squiggle) {
            svg = this.squigglePath();
        } else {
            svg = this.offsetLine(0, 0);
        }
        return svg;
    };


    /** A group of 1D curves. This was designed so that all of the
        methods can later be implemented in O(1) time, but it
        currently uses O(n) implementations for source code
        simplicity. */
    function PathSet() {
        this._pathArray = [];
    }

    const PS = PathSet.prototype;
    PS.insert = function (path) {
        this._pathArray.push(path);
    };

    /** Returns a new method that returns true if method(x, y)
        returns true on any element of _pathAray */
    function makeFilterAny(method) {
        return function (x, y) {
            for (let i = 0; i < this._pathArray.length; ++i) {
                if (method.call(this._pathArray[i], x, y)) { return true; }
            }
            // Fall through: return undefined == false
        }
    }

    // True if an up line ends at these coordinates. Recall that the
    // variable _ is bound to the Path prototype still.
    PS.upEndsAt = makeFilterAny(_.upEndsAt);
    PS.diagonalUpEndsAt = makeFilterAny(_.diagonalUpEndsAt);
    PS.backDiagonalUpEndsAt = makeFilterAny(_.backDiagonalUpEndsAt);
    PS.diagonalDownEndsAt = makeFilterAny(_.diagonalDownEndsAt);
    PS.backDiagonalDownEndsAt = makeFilterAny(_.backDiagonalDownEndsAt);
    PS.downEndsAt = makeFilterAny(_.downEndsAt);
    PS.leftEndsAt = makeFilterAny(_.leftEndsAt);
    PS.rightEndsAt = makeFilterAny(_.rightEndsAt);
    PS.endsAt = makeFilterAny(_.endsAt);
    PS.verticalPassesThrough = makeFilterAny(_.verticalPassesThrough);
    PS.horizontalPassesThrough = makeFilterAny(_.horizontalPassesThrough);

    /** Returns a new method that returns the first path where method(x, y) is true */
    function makeFilterFind(method) {
        return function (x, y) {
            for (let i = 0; i < this._pathArray.length; ++i) {
                if (method.call(this._pathArray[i], x, y)) { return this._pathArray[i]; }
            }
            return null;
        }
    }

    PS.findUpEndsAt = makeFilterFind(_.upEndsAt);
    PS.findDownEndsAt = makeFilterFind(_.downEndsAt);
    PS.findLeftEndsAt = makeFilterFind(_.leftEndsAt);
    PS.findRightEndsAt = makeFilterFind(_.rightEndsAt);
    PS.findDiagonalUpEndsAt = makeFilterFind(_.diagonalUpEndsAt);
    PS.findDiagonalDownEndsAt = makeFilterFind(_.diagonalDownEndsAt);
    PS.findBackDiagonalUpEndsAt = makeFilterFind(_.backDiagonalUpEndsAt);
    PS.findBackDiagonalDownEndsAt = makeFilterFind(_.backDiagonalDownEndsAt);
    PS.findHorizontalPassesThrough = makeFilterFind(_.horizontalPassesThrough);
    PS.findVerticalPassesThrough = makeFilterFind(_.verticalPassesThrough);

    /** Returns an SVG string */
    PS.toSVG = function () {
        let svg = '';
        for (let i = 0; i < this._pathArray.length; ++i) {
            svg += this._pathArray[i].toSVG() + '\n';
        }
        return svg;
    };


    function DecorationSet() {
        this._decorationArray = [];
        this._types = new Set();
    }

    const DS = DecorationSet.prototype;

    DS.has = function (typelist) {
        return Array.prototype.some.call(typelist, t => this._types.has(t));
    }

    /** insert(x, y, type, <angle>)
        insert(vec, type, <angle>)

        angle is the angle in degrees to rotate the result */
    DS.insert = function (x, y, type, angle) {
        if (type === undefined) { type = y; y = x.y; x = x.x; }

        if (!isDecoration(type)) {
            throw new Error('Illegal decoration character: ' + type);
        }
        const d = { C: Vec2(x, y), type: type, angle: angle || 0 };

        // Put arrows at the front and points at the back so that
        // arrows always draw under points
        if (isPoint(type)) {
            this._decorationArray.push(d);
        } else {
            this._decorationArray.unshift(d);
        }
        this._types.add(type);
    };

    // Compute offsets for line arrows.
    // Shift each side inward by W=STROKE_WIDTH/2 SVG px (perpendicular to the side)
    // so the outer edge of the stroke aligns with the solid polygon boundary.
    // H_SVG/L_SVG: half-base/length in SVG px; SL_SVG: side length in SVG px.
    const AH_B_SVG = ARROWHEAD_HALF_BASE * SCALE * ASPECT;
    const AH_L_SVG = ARROWHEAD_LENGTH * SCALE;
    const AH_LEN_SVG = Math.sqrt(AH_L_SVG ** 2 + AH_B_SVG ** 2);
    // ..._BASE_DX/DY: grid-coord displacement of base corners toward the axis.
    // ...TIP_DX: grid-x pullback of the tip (intersection of the two inset sides).
    const ARROWHEAD_LINE_BASE_DX = STROKE_WIDTH / 2 * AH_B_SVG / (AH_LEN_SVG * SCALE);
    const ARROWHEAD_LINE_BASE_DY = STROKE_WIDTH / 2 * AH_L_SVG / (AH_LEN_SVG * SCALE * ASPECT);
    const ARROWHEAD_LINE_TIP_DX = STROKE_WIDTH / 2 * AH_LEN_SVG / (AH_B_SVG * SCALE);

    DS.toSVG = function () {
        let svg = '';
        for (let i = 0; i < this._decorationArray.length; ++i) {
            const decoration = this._decorationArray[i];
            const C = decoration.C;

            if (isJump(decoration.type)) {
                // Slide jumps
                const dx = (decoration.type === ')') ? +0.75 : -0.75;
                const up = Vec2(C.x, C.y - 0.5);
                const dn = Vec2(C.x, C.y + 0.5);
                const cup = Vec2(C.x + dx, C.y - 0.5);
                const cdn = Vec2(C.x + dx, C.y + 0.5);

                svg += '<path class="jump" d="M ' + dn + 'C ' + cdn + cup + up.coords() + '"/>\n';

            } else if (isPoint(decoration.type)) {
                const CLASSES = { '*': 'closed', 'o': 'open', '◌': 'dotted', '○': 'open', '◍': 'shaded', '●': 'closed', '⊕': 'xor' };
                const cls = CLASSES[decoration.type];
                const cx = (C.x + 1) * SCALE, cy = (C.y + 1) * SCALE * ASPECT, rx = SCALE - STROKE_WIDTH;
                const [tag, radii] = (ASPECT === DEFAULT_ASPECT)
                    ? ['circle', 'r="' + rx + '"']
                    : ['ellipse', 'rx="' + rx + '" ry="' + (rx * ASPECT / DEFAULT_ASPECT) + '"'];
                svg += '<' + tag + ' cx="' + cx + '" cy="' + cy + '" ' + radii + ' class="dot ' + cls + '"/>\n';
                if (decoration.type === '⊕') {
                    svg += '<line x1="' + ((C.x) * SCALE + STROKE_WIDTH) +
                        '" y1="' + ((C.y + 1) * SCALE * ASPECT) +
                        '" x2="' + ((C.x + 2) * SCALE - STROKE_WIDTH) +
                        '" y2="' + ((C.y + 1) * SCALE * ASPECT) + '"/>';
                    svg += '<line x1="' + ((C.x + 1) * SCALE) +
                        '" y1="' + ((C.y + 1) * SCALE * ASPECT - SCALE + STROKE_WIDTH) +
                        '" x2="' + ((C.x + 1) * SCALE) +
                        '" y2="' + ((C.y + 1) * SCALE * ASPECT + SCALE - STROKE_WIDTH) + '"/>';
                }
            } else if (isGray(decoration.type)) {
                const shade = Math.round((3 - GRAY_CHARACTERS.indexOf(decoration.type)) * 63.75);
                svg += '<rect class="gray" x="' + ((C.x + 0.5) * SCALE) + '" y="' + ((C.y + 0.5) * SCALE * ASPECT) +
                    '" width="' + SCALE + '" height="' + (SCALE * ASPECT) +
                    '" fill="rgb(' + shade + ',' + shade + ',' + shade + ')"/>\n';
            } else if (isTri(decoration.type)) {
                // 30-60-90 triangle
                const index = TRI_CHARACTERS.indexOf(decoration.type);
                let xs = 0.5 - (index & 1);
                const ys = 0.5 - (index >> 1);
                xs *= sign(ys);
                const tip = Vec2(C.x + xs, C.y - ys);
                const up = Vec2(C.x + xs, C.y + ys);
                const dn = Vec2(C.x - xs, C.y + ys);
                svg += '<polygon class="triangle" points="' + tip + up + dn.coords(4) + '"/>\n';
            } else { // Arrow head
                let ah_len = ARROWHEAD_LENGTH, ah_hbase = ARROWHEAD_HALF_BASE;
                const angle_rad = decoration.angle * Math.PI / 180;
                const cos_a = Math.cos(angle_rad), sin_a = Math.sin(angle_rad);
                let tip = C;
                let up = Vec2(C.x - ah_len * cos_a + ah_hbase * ASPECT * sin_a,
                    C.y - ah_len * sin_a / ASPECT - ah_hbase * cos_a);
                let dn = Vec2(C.x - ah_len * cos_a - ah_hbase * ASPECT * sin_a,
                    C.y - ah_len * sin_a / ASPECT + ah_hbase * cos_a);
                if (options.arrow === 'line') {
                    const tip_dx = ARROWHEAD_LINE_TIP_DX;
                    const base_dx = ARROWHEAD_LINE_BASE_DX, base_dy = ARROWHEAD_LINE_BASE_DY;
                    // Vectors for forward and perpendicular adjustment to the line,
                    // so that the outer edge of the line matches the outer edge of the polygon.
                    const adj_fx = -base_dx * cos_a, adj_fy = -base_dx * sin_a / ASPECT;
                    const adj_px = base_dy * ASPECT * sin_a, adj_py = base_dy * cos_a;
                    tip = tip.offset(-tip_dx * cos_a, -tip_dx * sin_a / ASPECT);
                    up = up.offset(adj_fx - adj_px, adj_fy + adj_py);
                    dn = dn.offset(adj_fx + adj_px, adj_fy - adj_py);
                    svg += '<path class="arrowhead" d="M ' + up + 'L ' + tip + 'L ' + dn.coords() + '"/>\n';
                } else {
                    svg += '<polygon class="arrowhead" points="' + tip + up + dn.coords() + '"/>\n';
                }
            }
        }
        return svg;
    };

    ////////////////////////////////////////////////////////////////////////////

    function findPaths(grid, pathSet) {
        // Does the line from A to B contain at least one c?
        function lineContains(A, B, c) {
            const dx = sign(B.x - A.x);
            const dy = sign(B.y - A.y);
            let x, y;

            for (x = A.x, y = A.y; (x !== B.x) || (y !== B.y); x += dx, y += dy) {
                if (grid(x, y) === c) { return true; }
            }

            // Last point
            return (grid(x, y) === c);
        }

        // Find all solid vertical lines. Iterate horizontally
        // so that we never hit the same line twice
        for (let x = 0; x < grid.width; ++x) {
            for (let y = 0; y < grid.height; ++y) {
                function vline(p, alt, boxt, boxb, style) {
                    if (grid[p](x, y) ||
                        (grid(x, y) === '^' && (grid(x, y - 1) === 'v' || grid(x, y - 1) === 'V') && grid[p](x, y + 1))) {
                        // This character begins a vertical line...now, find the end
                        const A = Vec2(x, y);
                        do { grid.setUsed(x, y); ++y; } while (grid[p](x, y));
                        const B = Vec2(x, y - 1);

                        const up = grid(A);
                        const upup = grid(A.x, A.y - 1);

                        if (!isVertex(up) && ((upup === '-') || (upup === '_') ||
                            (boxt.indexOf(upup) >= 0) ||
                            (grid(A.x - 1, A.y - 1) === '_') ||
                            (grid(A.x + 1, A.y - 1) === '_') ||
                            isBottomVertex(upup)) || isJump(upup) ||
                            (grid[alt](A.x, A.y - 1) && !isVertex(upup))) {
                            // Stretch up to almost reach the line above (if there is a decoration,
                            // it will finish the gap)
                            A.y -= (isVertex(upup) && grid[alt](A.x, A.y - 2) && !isTopVertexOrDecoration(up)) ? 1 : 0.5;
                        }

                        const dn = grid(B);
                        const dndn = grid(B.x, B.y + 1);
                        if (!isVertex(dn) && ((dndn === '-') || (boxb.indexOf(dndn) >= 0) || isTopVertex(dndn)) || isJump(dndn) ||
                            (grid(B.x - 1, B.y) === '_') || (grid(B.x + 1, B.y) === '_') ||
                            (grid[alt](B.x, B.y + 1) && !isVertex(dn))) {
                            // Stretch down to almost reach the line below
                            B.y += 0.5;
                        }

                        // Don't insert degenerate lines
                        if ((A.x !== B.x) || (A.y !== B.y)) {
                            pathSet.insert(new Path(A, B, null, null, style));
                            // Re-evaluate the character we just rejected.
                            --y;
                            return true;
                        }

                        // Continue the search from y+1.
                    }
                    return false;
                }

                if (vline("isSolidVLineAt", "isDoubleVLineAt", '\u2564', '\u2567') ||
                    vline("isSquiggleVLineAt", "isSolidVLineAt", '', '', "squiggle") ||
                    vline("isDoubleVLineAt", "isSolidVLineAt", '\u2565\u2566', '\u2568\u2569', "double")) {
                    continue;
                }

                // Some very special patterns for the short lines needed on
                // circuit diagrams. Only invoke these if not also on a curve
                //      _  _
                //    -'    '-   -'
                if ((grid(x, y) === "'") &&
                    (((grid(x - 1, y) === '-') && (grid(x + 1, y - 1) === '_') &&
                        !isSolidVLineOrJumpOrPoint(grid(x - 1, y - 1))) ||
                        ((grid(x - 1, y - 1) === '_') && (grid(x + 1, y) === '-') &&
                            !isSolidVLineOrJumpOrPoint(grid(x + 1, y - 1))))) {
                    pathSet.insert(new Path(Vec2(x, y - 0.5), Vec2(x, y)));
                }

                //    _.-  -._
                else if ((grid(x, y) === '.') &&
                    (((grid(x - 1, y) === '_') && (grid(x + 1, y) === '-') &&
                        !isSolidVLineOrJumpOrPoint(grid(x + 1, y + 1))) ||
                        ((grid(x - 1, y) === '-') && (grid(x + 1, y) === '_') &&
                            !isSolidVLineOrJumpOrPoint(grid(x - 1, y + 1))))) {
                    pathSet.insert(new Path(Vec2(x, y), Vec2(x, y + 0.5)));
                }

                // For drawing resistors: -.╱
                else if ((grid(x, y) === '.') &&
                    (grid(x - 1, y) === '-') &&
                    (grid(x + 1, y) === '\u2571')) {
                    pathSet.insert(new Path(Vec2(x, y), Vec2(x + 0.5, y + 0.5)));
                }

                // For drawing resistors: ╱'-
                else if ((grid(x, y) === "'") &&
                    (grid(x + 1, y) === '-') &&
                    (grid(x - 1, y) === '\u2571')) {
                    pathSet.insert(new Path(Vec2(x, y), Vec2(x - 0.5, y - 0.5)));
                }

            } // y
        } // x


        // Find all solid horizontal lines
        for (let y = 0; y < grid.height; ++y) {
            for (let x = 0; x < grid.width; ++x) {
                function hline(p, boxl, boxr, style) {
                    if (grid[p](x, y) || (grid(x, y) === '<' && grid(x - 1, y) === '>' && grid[p](x + 1, y))) {
                        // Begins a line...find the end
                        const A = Vec2(x, y);
                        do { grid.setUsed(x, y); ++x; } while (grid[p](x, y));
                        const B = Vec2(x - 1, y);

                        // Detect adjacent box-drawing characters and lengthen the edge
                        if (boxr.indexOf(grid(B.x + 1, B.y)) >= 0) { B.x += 0.5; }
                        if (boxl.indexOf(grid(A.x - 1, A.y)) >= 0) { A.x -= 0.5; }

                        // Detect curves and shorten the edge
                        if (!isVertex(grid(A.x - 1, A.y)) &&
                            ((isTopVertex(grid(A)) && isSolidVLineOrJumpOrPoint(grid(A.x - 1, A.y + 1))) ||
                                (isBottomVertex(grid(A)) && isSolidVLineOrJumpOrPoint(grid(A.x - 1, A.y - 1))))) {
                            ++A.x;
                        } else if (!isVertexOrLeftDecoration(grid(A)) &&
                            isVertex(grid(A.x - 1, A.y)) &&
                            grid.isAnyHLineAt(A.x - 2, A.y)) {
                            // Line continuation, changing type.
                            --A.x;
                        } else if (grid.isAnyHLineAt(A.x - 1, A.y) &&
                            !isVertexOrRightDecoration(grid(A.x - 1, A.y)) &&
                            !isVertex(grid(A))) {
                            A.x -= 0.5;
                        }

                        if (!isVertex(grid(B.x + 1, B.y)) &&
                            ((isTopVertex(grid(B)) && isSolidVLineOrJumpOrPoint(grid(B.x + 1, B.y + 1))) ||
                                (isBottomVertex(grid(B)) && isSolidVLineOrJumpOrPoint(grid(B.x + 1, B.y - 1))))) {
                            --B.x;
                        } else if (grid.isAnyHLineAt(B.x + 1, B.y) &&
                            !isVertexOrLeftDecoration(grid(B.x + 1, B.y)) &&
                            !isVertex(grid(B))) {
                            B.x += 0.5;
                        }

                        // Only insert non-degenerate lines
                        if ((A.x !== B.x) || (A.y !== B.y)) {
                            pathSet.insert(new Path(A, B, null, null, style));
                            // Re-evaluate the character we just rejected.
                            --x;
                            return true;
                        }

                        // Continue the search from x+1.
                    }
                    return false;
                }

                hline("isSolidHLineAt", '\u2523', '\u252b', null) ||
                    hline("isSquiggleHLineAt", '\u2523', '\u252b', "squiggle") ||
                    hline("isDoubleHLineAt", '\u255E', '\u2561', "double");
            }
        } // y

        // Find all solid left-to-right downward diagonal lines (BACK DIAGONAL)
        for (let i = -grid.height; i < grid.width; ++i) {
            for (let x = i, y = 0; y < grid.height; ++y, ++x) {
                if (grid.isSolidBLineAt(x, y)) {
                    // Begins a line...find the end
                    const A = Vec2(x, y);
                    do { ++x; ++y; } while (grid.isSolidBLineAt(x, y));
                    const B = Vec2(x - 1, y - 1);

                    // Ensure that the entire line wasn't just vertices
                    if (lineContains(A, B, '\\')) {
                        for (let j = A.x; j <= B.x; ++j) {
                            grid.setUsed(j, A.y + (j - A.x));
                        }

                        const top = grid(A);
                        const up = grid(A.x, A.y - 1);
                        const uplt = grid(A.x - 1, A.y - 1);
                        if ((up === '/') || (uplt === '_') || (up === '_') ||
                            (!isVertex(top) &&
                                (isSolidHLine(uplt) || isSolidVLine(uplt)))) {
                            // Continue half a cell more to connect for:
                            //  ___   ___
                            //  \        \    /      ----     |
                            //   \        \   \        ^      |^
                            A.x -= 0.5; A.y -= 0.5;
                        } else if (isPoint(uplt)) {
                            // Continue 1/4 cell more to connect for:
                            //
                            //  o
                            //   ^
                            //    \
                            A.x -= 0.25; A.y -= 0.25;
                        } else if (top === '\\' && grid.isSolidDLineAt(A.x - 1, A.y)) {
                            // Cap a sharp vertex:
                            //   \  /   \  _
                            //    \/     \/
                            A.x -= 0.5; A.y -= 0.5;
                        }

                        const bottom = grid(B);
                        const dnrt = grid(B.x + 1, B.y + 1);
                        if ((grid(B.x, B.y + 1) === '/') || (grid(B.x + 1, B.y) === '_') ||
                            (grid(B.x - 1, B.y) === '_') ||
                            (!isVertex(grid(B)) &&
                                (isSolidHLine(dnrt) || isSolidVLine(dnrt)))) {
                            // Continue half a cell more to connect for:
                            //                       \      \ |
                            //  \       \     \       v      v|
                            //   \__   __\    /      ----     |

                            B.x += 0.5; B.y += 0.5;
                        } else if (isPoint(dnrt)) {
                            // Continue 1/4 cell more to connect for:
                            //
                            //    \
                            //     v
                            //      o

                            B.x += 0.25; B.y += 0.25;
                        } else if (bottom === '\\' && grid.isSolidDLineAt(B.x + 1, B.y)) {
                            // Cap a sharp vertex:
                            //     /\   _/\
                            //    /  \     \
                            B.x += 0.5; B.y += 0.5;
                        }

                        pathSet.insert(new Path(A, B));
                        // Continue the search from the end x+1,y+1
                    } // lineContains
                }
            }
        } // i


        // Find all solid left-to-right upward diagonal lines (DIAGONAL)
        for (let i = -grid.height; i < grid.width; ++i) {
            for (let x = i, y = grid.height - 1; y >= 0; --y, ++x) {
                if (grid.isSolidDLineAt(x, y)) {
                    // Begins a line...find the end
                    const A = Vec2(x, y);
                    do { ++x; --y; } while (grid.isSolidDLineAt(x, y));
                    const B = Vec2(x - 1, y + 1);

                    if (lineContains(A, B, '/')) {
                        // This is definitely a line. Commit the characters on it
                        for (let j = A.x; j <= B.x; ++j) {
                            grid.setUsed(j, A.y - (j - A.x));
                        }

                        const up = grid(B.x, B.y - 1);
                        const uprt = grid(B.x + 1, B.y - 1);
                        const bottom = grid(B);
                        if ((up === '\\') || (up === '_') || (uprt === '_') ||
                            (!isVertex(grid(B)) &&
                                (isSolidHLine(uprt) || isSolidVLine(uprt)))) {

                            // Continue half a cell more to connect at:
                            //     __   __  ---     |
                            //    /      /   ^     ^|
                            //   /      /   /     / |

                            B.x += 0.5; B.y -= 0.5;
                        } else if (isPoint(uprt)) {

                            // Continue 1/4 cell more to connect at:
                            //
                            //       o
                            //      ^
                            //     /

                            B.x += 0.25; B.y -= 0.25;
                        } if (bottom === '/' && grid.isSolidBLineAt(B.x + 1, B.y)) {
                            // Cap a sharp vertex:
                            //   \  /   \  _
                            //    \/     \/
                            B.x += 0.5; B.y -= 0.5;
                        }

                        const dnlt = grid(A.x - 1, A.y + 1);
                        const top = grid(A);
                        if ((grid(A.x, A.y + 1) === '\\') || (grid(A.x - 1, A.y) === '_') || (grid(A.x + 1, A.y) === '_') ||
                            (!isVertex(grid(A)) &&
                                (isSolidHLine(dnlt) || isSolidVLine(dnlt)))) {

                            // Continue half a cell more to connect at:
                            //               /     \ |
                            //    /  /      v       v|
                            // __/  /__   ----       |

                            A.x -= 0.5; A.y += 0.5;
                        } else if (isPoint(dnlt)) {

                            // Continue 1/4 cell more to connect at:
                            //
                            //       /
                            //      v
                            //     o

                            A.x -= 0.25; A.y += 0.25;
                        } else if (top === '/' && grid.isSolidBLineAt(A.x - 1, A.y)) {
                            // Cap a sharp vertex:
                            //    \  /    _  /
                            //     \/      \/
                            A.x -= 0.5; A.y += 0.5;
                        }
                        pathSet.insert(new Path(A, B));

                        // Continue the search from the end x+1,y-1
                    } // lineContains
                }
            }
        } // y


        // Now look for curved corners. The syntax constraints require
        // that these can always be identified by looking at three
        // horizontally-adjacent characters.
        for (let y = 0; y < grid.height; ++y) {
            for (let x = 0; x < grid.width; ++x) {
                const CURVE = 0.551915024494; // https://spencermortensen.com/articles/bezier-circle/
                const CURVE_X = 2 * CURVE;
                const CURVE_Y = CURVE;
                const c = grid(x, y);

                // Note that because of undirected vertices, the
                // following cases are not exclusive
                if (isTopVertex(c)) {
                    // -.
                    //   |
                    if (isSolidHLine(grid(x - 1, y)) && isSolidVLine(grid(x + 1, y + 1))) {
                        grid.setUsed(x - 1, y); grid.setUsed(x, y); grid.setUsed(x + 1, y + 1);
                        pathSet.insert(new Path(Vec2(x - 1, y), Vec2(x + 1, y + 1),
                            Vec2(x - 1 + CURVE_X, y), Vec2(x + 1, y + 1 - CURVE_Y)));
                    }

                    //  .-
                    // |
                    if (isSolidHLine(grid(x + 1, y)) && isSolidVLine(grid(x - 1, y + 1))) {
                        grid.setUsed(x - 1, y + 1); grid.setUsed(x, y); grid.setUsed(x + 1, y);
                        pathSet.insert(new Path(Vec2(x + 1, y), Vec2(x - 1, y + 1),
                            Vec2(x + 1 - CURVE_X, y), Vec2(x - 1, y + 1 - CURVE_Y)));
                    }
                }

                // Special case patterns:
                //   .  .   .  .
                //  (  o     )  o
                //   '  .   '  '
                // Left curve:
                if ((c === '(') && (grid(x + 1, y - 1) === '.') && (grid(x + 1, y + 1) === "\'")) {
                    grid.setUsed(x, y); grid.setUsed(x + 1, y - 1); grid.setUsed(x + 1, y + 1);
                    pathSet.insert(new Path(Vec2(x + 2, y - 1), Vec2(x + 2, y + 1),
                        Vec2(x - 0.6, y - 1), Vec2(x - 0.6, y + 1)));
                }
                if (isPoint(c) && (grid(x + 1, y - 1) === '.') && (grid(x + 1, y + 1) === "\'") &&
                    !grid.isUsed(x + 1, y - 1) && !grid.isUsed(x + 1, y + 1)) {
                    grid.setUsed(x, y); grid.setUsed(x + 1, y - 1); grid.setUsed(x + 1, y + 1);
                    pathSet.insert(new Path(Vec2(x + 2, y - 1), Vec2(x + 2, y + 1),
                        Vec2(x - 0.6, y - 1), Vec2(x - 0.6, y + 1)));
                }

                // Right curve:
                if ((c === ')') && (grid(x - 1, y - 1) === '.') && (grid(x - 1, y + 1) === "\'")) {
                    grid.setUsed(x, y); grid.setUsed(x - 1, y - 1); grid.setUsed(x - 1, y + 1);
                    pathSet.insert(new Path(Vec2(x - 2, y - 1), Vec2(x - 2, y + 1),
                        Vec2(x + 0.6, y - 1), Vec2(x + 0.6, y + 1)));
                }
                if (isPoint(c) && (grid(x - 1, y - 1) === '.') && (grid(x - 1, y + 1) === "\'") &&
                    !grid.isUsed(x - 1, y - 1) && !grid.isUsed(x - 1, y + 1)) {
                    grid.setUsed(x, y); grid.setUsed(x - 1, y - 1); grid.setUsed(x - 1, y + 1);
                    pathSet.insert(new Path(Vec2(x - 2, y - 1), Vec2(x - 2, y + 1),
                        Vec2(x + 0.6, y - 1), Vec2(x + 0.6, y + 1)));
                }


                if (isBottomVertex(c)) {
                    //   |
                    // -'
                    if (isSolidHLine(grid(x - 1, y)) && isSolidVLine(grid(x + 1, y - 1))) {
                        grid.setUsed(x - 1, y); grid.setUsed(x, y); grid.setUsed(x + 1, y - 1);
                        pathSet.insert(new Path(Vec2(x - 1, y), Vec2(x + 1, y - 1),
                            Vec2(x - 1 + CURVE_X, y), Vec2(x + 1, y - 1 + CURVE_Y)));
                    }

                    // |
                    //  '-
                    if (isSolidHLine(grid(x + 1, y)) && isSolidVLine(grid(x - 1, y - 1))) {
                        grid.setUsed(x - 1, y - 1); grid.setUsed(x, y); grid.setUsed(x + 1, y);
                        pathSet.insert(new Path(Vec2(x + 1, y), Vec2(x - 1, y - 1),
                            Vec2(x + 1 - CURVE_X, y), Vec2(x - 1, y - 1 + CURVE_Y)));
                    }
                }

            } // for x
        } // for y

        // Find low horizontal lines marked with underscores. These
        // are so simple compared to the other cases that we process
        // them directly here without a helper function. Process these
        // from top to bottom and left to right so that we can read
        // them in a single sweep.
        //
        // Exclude the special case of double underscores going right
        // into an ASCII character, which could be a source code
        // identifier such as __FILE__ embedded in the diagram.
        for (let y = 0; y < grid.height; ++y) {
            for (let x = 0; x < grid.width - 2; ++x) {
                let lt = grid(x - 1, y);

                if ((grid(x, y) === '_') && (grid(x + 1, y) === '_') &&
                    (!isASCIILetter(grid(x + 2, y)) || (lt === '_')) &&
                    (!isASCIILetter(lt) || (grid(x + 2, y) === '_'))) {

                    let ltlt = grid(x - 2, y);
                    const A = Vec2(x - 0.5, y + 0.5);

                    if ((lt === '|') || (grid(x - 1, y + 1) === '|') ||
                        (lt === '.') || (grid(x - 1, y + 1) === "'")) {
                        // Extend to meet adjacent vertical
                        A.x -= 0.5;

                        // Very special case of overrunning into the side of a curve,
                        // needed for logic gate diagrams
                        if ((lt === '.') &&
                            ((ltlt === '-') ||
                                (ltlt === '.')) &&
                            (grid(x - 2, y + 1) === '(')) {
                            A.x -= 0.5;
                        }
                    } else if (lt === '/') {
                        A.x -= 1.0;
                    }

                    // Detect overrun of a tight double curve
                    if ((lt === '(') && (ltlt === '(') &&
                        (grid(x, y + 1) === "'") && (grid(x, y - 1) === '.')) {
                        A.x += 0.5;
                    }
                    lt = ltlt = undefined;

                    do { grid.setUsed(x, y); ++x; } while (grid(x, y) === '_');

                    const B = Vec2(x - 0.5, y + 0.5);
                    const c = grid(x, y);
                    const rt = grid(x + 1, y);
                    const dn = grid(x, y + 1);

                    if ((c === '|') || (dn === '|') || (c === '.') || (dn === "'")) {
                        // Extend to meet adjacent vertical
                        B.x += 0.5;

                        // Very special case of overrunning into the side of a curve,
                        // needed for logic gate diagrams
                        if ((c === '.') &&
                            ((rt === '-') || (rt === '.')) &&
                            (grid(x + 1, y + 1) === ')')) {
                            B.x += 0.5;
                        }
                    } else if ((c === '\\')) {
                        B.x += 1.0;
                    }

                    // Detect overrun of a tight double curve
                    if ((c === ')') && (rt === ')') && (grid(x - 1, y + 1) === "'") && (grid(x - 1, y - 1) === '.')) {
                        B.x += -0.5;
                    }

                    pathSet.insert(new Path(A, B));
                }
            } // for x
        } // for y
    } // findPaths


    function findDecorations(grid, pathSet, decorationSet) {
        function isEmptyOrVertex(c) { return (c === ' ') || /[^a-zA-Z0-9]|[ov]/.test(c); }

        /** Compute the tip position of an arrowhead with center (cx, cy) and rotation angle (degrees). */
        function arrowTip(cx, cy, angle) {
            const angle_rad = angle * Math.PI / 180;
            return Vec2(cx + Math.cos(angle_rad), cy + Math.sin(angle_rad) / DEFAULT_ASPECT);
        }

        /** Is the point in the center of these values on a line? Allow points that are vertically
            adjacent but not horizontally--they wouldn't fit anyway, and might be text. */
        function onLine(up, dn, lt, rt) {
            return ((isEmptyOrVertex(dn) || isPoint(dn)) &&
                (isEmptyOrVertex(up) || isPoint(up)) &&
                isEmptyOrVertex(rt) &&
                isEmptyOrVertex(lt));
        }

        for (let x = 0; x < grid.width; ++x) {
            for (let j = 0; j < grid.height; ++j) {
                const c = grid(x, j);
                const y = j;

                function tryArrow(methodName, px, py, angle, companionMethod) {
                    const p = pathSet[methodName](px, py);
                    if (p) {
                        const tip = arrowTip(px, py, angle);
                        decorationSet.insert(tip.x, tip.y, '>', angle);
                        grid.setUsed(x, y);
                        p.markArrowAt(px, py, 'end', tip);
                        if (companionMethod) {
                            const q = pathSet[companionMethod](px, py);
                            if (q) q.markArrowAt(px, py, 'none', tip);
                        }
                    }
                    return !!p;
                }

                if (isJump(c)) {

                    // Ensure that this is really a jump and not a stray character
                    if (pathSet.downEndsAt(x, y - 0.5) &&
                        pathSet.upEndsAt(x, y + 0.5)) {
                        decorationSet.insert(x, y, c);
                        grid.setUsed(x, y);
                    }

                } else if (isPoint(c)) {
                    const up = grid(x, y - 1);
                    const dn = grid(x, y + 1);
                    const lt = grid(x - 1, y);
                    const rt = grid(x + 1, y);

                    if (pathSet.rightEndsAt(x - 1, y) ||   // Must be at the end of a line...
                        pathSet.leftEndsAt(x + 1, y) ||    // or completely isolated NSEW
                        pathSet.downEndsAt(x, y - 1) ||
                        pathSet.upEndsAt(x, y + 1) ||

                        pathSet.upEndsAt(x, y) ||    // For points on vertical lines
                        pathSet.downEndsAt(x, y) ||  // that are surrounded by other characters

                        onLine(up, dn, lt, rt)) {

                        decorationSet.insert(x, y, c);
                        grid.setUsed(x, y);
                    }
                } else if (isGray(c)) {
                    decorationSet.insert(x, y, c);
                    grid.setUsed(x, y);
                } else if (isTri(c)) {
                    decorationSet.insert(x, y, c);
                    grid.setUsed(x, y);
                } else { // Arrow heads

                    // If we find one, ensure that it is really an
                    // arrow head and not a stray character by looking
                    // for a connecting line.
                    const BACKOFF_X = 0.5;
                    const BACKOFF_Y = 0.5 / ASPECT;
                    let dx = 0;
                    let dy = 0;
                    if (c === '>') {
                        const p = pathSet.findRightEndsAt(x, y);
                        const q = !p ? pathSet.findHorizontalPassesThrough(x, y) : null;
                        if (p || q) {
                            if (isPoint(grid(x + 1, y)) || grid(x + 1, y) === '<' || grid(x + 1, y) === '>') { dx = -BACKOFF_X; }
                            const tip = arrowTip(x + dx, y, 0);
                            decorationSet.insert(tip.x, tip.y, '>', 0);
                            grid.setUsed(x, y);
                            if (p) { p.markArrowAt(x, y, 'end', tip); } else { q.markArrowContRight(tip); }
                        }
                    } else if (c === '<') {
                        const p = pathSet.findLeftEndsAt(x, y);
                        const q = !p ? pathSet.findHorizontalPassesThrough(x, y) : null;
                        if (p || q) {
                            if (isPoint(grid(x - 1, y)) || grid(x - 1, y) === '>' || grid(x - 1, y) === '<') { dx = BACKOFF_X; }
                            const tip = arrowTip(x + dx, y, 180);
                            decorationSet.insert(tip.x, tip.y, '>', 180);
                            grid.setUsed(x, y);
                            if (p) { p.markArrowAt(x, y, 'end', tip); } else { q.markArrowContLeft(tip); }
                        }
                    } else if (c === '^') {
                        // Because of the aspect ratio, we need to look
                        // in two slots for the end of the previous line
                        if (!tryArrow('findUpEndsAt', x, y - 0.5, 270, 'findDownEndsAt') &&
                            !tryArrow('findUpEndsAt', x, y, 270, 'findDownEndsAt') &&
                            !tryArrow('findDiagonalUpEndsAt', x + 0.5, y - 0.5, 270 + DIAGONAL_ANGLE) &&
                            !tryArrow('findDiagonalUpEndsAt', x + 0.25, y - 0.25, 270 + DIAGONAL_ANGLE) &&
                            !tryArrow('findDiagonalUpEndsAt', x, y, 270 + DIAGONAL_ANGLE) &&
                            !tryArrow('findBackDiagonalUpEndsAt', x, y, 270 - DIAGONAL_ANGLE) &&
                            !tryArrow('findBackDiagonalUpEndsAt', x - 0.5, y - 0.5, 270 - DIAGONAL_ANGLE) &&
                            !tryArrow('findBackDiagonalUpEndsAt', x - 0.25, y - 0.25, 270 - DIAGONAL_ANGLE) &&
                            pathSet.verticalPassesThrough(x, y)) {
                            // Only try this if all others failed
                            if (isPoint(grid(x, y - 1))) { dy = BACKOFF_Y; }
                            const tip270 = arrowTip(x, y - 0.5 + dy, 270);
                            decorationSet.insert(tip270.x, tip270.y, '>', 270);
                            grid.setUsed(x, y);
                            const q = pathSet.findVerticalPassesThrough(x, y);
                            if (q) { q.markArrowContUp(tip270); }
                        }
                    } else if (c === 'v' || c === 'V') {
                        if (!tryArrow('findDownEndsAt', x, y + 0.5, 90, 'findUpEndsAt') &&
                            !tryArrow('findDownEndsAt', x, y, 90, 'findUpEndsAt') &&
                            !tryArrow('findDiagonalDownEndsAt', x, y, 90 + DIAGONAL_ANGLE) &&
                            !tryArrow('findDiagonalDownEndsAt', x - 0.5, y + 0.5, 90 + DIAGONAL_ANGLE) &&
                            !tryArrow('findDiagonalDownEndsAt', x - 0.25, y + 0.25, 90 + DIAGONAL_ANGLE) &&
                            !tryArrow('findBackDiagonalDownEndsAt', x, y, 90 - DIAGONAL_ANGLE) &&
                            !tryArrow('findBackDiagonalDownEndsAt', x + 0.5, y + 0.5, 90 - DIAGONAL_ANGLE) &&
                            !tryArrow('findBackDiagonalDownEndsAt', x + 0.25, y + 0.25, 90 - DIAGONAL_ANGLE) &&
                            pathSet.verticalPassesThrough(x, y)) {
                            // Only try this if all others failed
                            if (isPoint(grid(x, y + 1))) { dy = -BACKOFF_Y; }
                            const tip90 = arrowTip(x, y + 0.5 + dy, 90);
                            decorationSet.insert(tip90.x, tip90.y, '>', 90);
                            grid.setUsed(x, y);
                            const q = pathSet.findVerticalPassesThrough(x, y);
                            if (q) { q.markArrowContDown(tip90); }
                        }
                    } // arrow heads
                } // decoration type
            } // y
        } // x
    } // findArrowHeads

    // Cases where we want to redraw at graphical unicode character
    // to adjust its weight or shape for a conventional application
    // in constructing a diagram.
    function findReplacementCharacters(grid, pathSet) {
        for (let x = 0; x < grid.width; ++x) {
            for (let y = 0; y < grid.height; ++y) {
                if (grid.isUsed(x, y)) continue;
                const c = grid(x, y);
                switch (c) {
                    case '╱':
                        pathSet.insert(new Path(Vec2(x - 0.5, y + 0.5), Vec2(x + 0.5, y - 0.5)));
                        grid.setUsed(x, y);
                        break;
                    case '╲':
                        pathSet.insert(new Path(Vec2(x - 0.5, y - 0.5), Vec2(x + 0.5, y + 0.5)));
                        grid.setUsed(x, y);
                        break;
                }
            }
        }
    } // findReplacementCharacters

    const grid = makeGrid(diagramString);

    const pathSet = new PathSet();
    const decorationSet = new DecorationSet();

    findPaths(grid, pathSet);
    findReplacementCharacters(grid, pathSet);
    findDecorations(grid, pathSet, decorationSet);

    const width = ((options.width || grid.width) + 1) * SCALE;
    const height = ((options.height || grid.height) + 1) * SCALE * ASPECT;
    if ((options.width && options.width < grid.width) ||
        (options.height && options.height < grid.height)) {
        console.warn("warning: diagram overflows viewbox set by width/height option");
    }
    const attrs = options.style;
    attrs.xmlns = 'http://www.w3.org/2000/svg';
    attrs.version = '1.1';
    if (!options.fill) {
        attrs.height = height.toString();
        attrs.width = width.toString();
    }
    attrs.viewBox = '0 0 ' + width + ' ' + height;
    // These attributes can be overridden:
    const DEFAULT_ATTRS = {
        'class': 'aasvg',
    };
    Object.keys(DEFAULT_ATTRS).forEach(k => {
        if (!attrs[k]) { attrs[k] = DEFAULT_ATTRS[k]; }
    });
    const hasText = !options.disableText && grid.hasText();
    let svg = '<svg ' + Object.keys(attrs)
        .filter(k => typeof attrs[k] === 'string')
        .map(k => k + '="' + escapeHTMLEntities(attrs[k]) + '"').join(' ') + '>\n';

    svg += '<style>\n';
    let black = 'black';
    let white = 'white';
    if (!options.compatible) {
        svg += ':root { color-scheme: light dark; ' +
            '--aasvg-b: light-dark(black, white); --aasvg-w: light-dark(white, black); }\n';
        black = 'var(--aasvg-b)';
        white = 'var(--aasvg-w)';
    }
    svg += `* { fill: none; stroke: ${black}; stroke-linecap: round;` +
        ((STROKE_WIDTH !== 1) ? ` stroke-width: ${STROKE_WIDTH};` : '') +
        ' }\n' +
        '.dashed { stroke-dasharray: 3,6; }\n';
    if (hasText || options.source) {
        svg += `text { font: ${fp(SCALE * 13 / 8)}px monospace;` +
            ` text-anchor: middle; fill: ${black}; stroke: none; }\n`;
    }
    if (hasText) {
        svg += 'text.b { font-weight: 700; }\n' +
            'text.i { font-style: italic; }\n';
    }
    if ((decorationSet.has('>') && options.arrow === 'solid') || decorationSet.has(TRI_CHARACTERS)) {
        svg += `polygon.arrowhead, .triangle { fill: ${black}; stroke: none; }\n`;
    }
    if (decorationSet.has(POINT_CHARACTERS)) {
        svg += `.dot.closed { fill: ${black}; }\n` +
            `.dot:is(.open, .xor) { fill: ${white}; }\n` +
            `.dot.dotted { fill: ${white}; stroke-dasharray: 0,1.8; }\n` +
            '.dot.shaded { fill: #666; }\n';
    }
    if (options.backdrop) {
        svg += `.backdrop { fill: ${white}; stroke: none; opacity: 0.9; }\n`;
    }
    if (options.grid) {
        svg += '.grid rect { stroke: none; fill: grey; opacity: 0.1; }\n' +
            '.grid rect.t { fill: blue; }\n' +
            '.grid rect.l { fill: red; }\n';
    }
    if (options.source) {
        svg += 'text { opacity: 0.8; }\n' +
            '.source { fill: red; font-size: 90%; }\n';
    }
    svg += '</style>\n';

    if (options.embed) {
        svg += '<text class="ascii" display="none"><![CDATA[\n'
            + originalString.split("\n").map(line => line.trimEnd()).join("\n")
            + ']]></text>\n';
    }

    if (options.backdrop) {
        svg += '<rect class="backdrop" x="0" y="0" width="' + ((grid.width + 1) * SCALE)
            + '" height="' + ((grid.height + 1) * SCALE * ASPECT)
            + '" rx="3px" ry="3px"/>\n';
    }
    if (options.grid) {
        svg += '<g class="grid">\n';
        for (let x = 0; x < grid.width; ++x) {
            for (let y = 0; y < grid.height; ++y) {
                svg += '<rect x="' + ((x + 0.5) * SCALE + 1) +
                    '" y="' + ((y + 0.5) * SCALE * ASPECT + 2) +
                    '" width="' + (SCALE - 2) + '" height="' + (SCALE * ASPECT - 2) + '"';
                if (grid.isUsed(x, y)) {
                    svg += ' class="l"';
                } else if (grid(x, y) !== ' ') {
                    svg += ' class="t"';
                }
                svg += '/>\n';
            }
        }
        svg += '</g>\n';
    }

    svg += pathSet.toSVG();
    svg += decorationSet.toSVG();

    // Convert any remaining characters
    if (hasText) {
        svg += '<g class="text">\n';
        // Enlarge hexagons so that they fill a grid
        for (let y = 0; y < grid.height; ++y) {
            for (let x = 0; x < grid.width; ++x) {
                const c = grid(x, y);
                if (/[\u2B22\u2B21]/.test(c)) {
                    svg += '<text x="' + ((x + 1) * SCALE) +
                        '" y="' + (4 + (y + 1) * SCALE * ASPECT) + '">' +
                        escapeHTMLEntities(unhideMarkers(c)) + '</text>\n';
                    grid.setUsed(x, y);
                }
            } // x
        } // y
        for (let y = 0; y < grid.height; ++y) {
            let x = grid.textStart(0, y);
            while (x < grid.width) {
                const t = grid.text(x, y);
                const s = t.join('');
                let displayText = s;
                let textClass = '';
                if (s.length >= 2 && s[0] === '*' && s[s.length - 1] === '*') {
                    displayText = s.slice(1, -1);
                    textClass = ' class="b"';
                } else if (s.length >= 2 && s[0] === '/' && s[s.length - 1] === '/') {
                    displayText = s.slice(1, -1);
                    textClass = ' class="i"';
                }
                svg += '<text x="' + ((x + (t.length / 2) + 0.5) * SCALE) +
                    '" y="' + (4 + (y + 1) * SCALE * ASPECT);
                if (options.spaces > 2 && s.indexOf('  ') >= 0) {
                    svg += '" xml:space="preserve';
                }
                if (options.stretch) {
                    svg += '" textLength="' + ((t.length - (textClass ? 2 : 0)) * SCALE) +
                        '" lengthAdjust="spacingAndGlyphs';
                }
                svg += '"' + textClass + '>' + escapeHTMLEntities(unhideMarkers(displayText)) + '</text>\n';
                x = grid.textStart(x + t.length, y);
            }
        } // y
        svg += '</g>\n';
    }

    if (options.source) {
        svg += '<g class="source">\n';
        for (let y = 0; y < grid.height; ++y) {
            for (let x = 0; x < grid.width; ++x) {
                const c = grid(x, y);
                if (c !== ' ') {
                    // Offset the characters by 2 for easier viewing
                    svg += '<text x="' + ((x + 1) * SCALE + 2) +
                        '" y="' + (6 + (y + 1) * SCALE * ASPECT) + '">' +
                        escapeHTMLEntities(unhideMarkers(c)) + '</text>';
                } // if
            } // x
        } // y
        svg += '</g>';
    } // if

    svg += '</svg>';

    return svg;
}

export { diagramToSVG };
